### ISSUE TITLE
Compile feedback on the RSpace Tutorial

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#594]
In the spirit of #301, Compile feedback on the [RSpace Tutorial](https://github.com/rchain/rchain/blob/master/rspace/docs/Tutorial.md).

I was going to post this directly to the [forum](https://forum.rchain.coop/), but I noticed that:
1. There is no RSpace topic grouping.
2. I find formatting comments in that forum an absolute nightmare. (Is it just me? someone help please)

**Measure of Completion**

- [ ] Compiled feedback delivered to core dev team

**Comment by Jake-Gillberg** [comment]
One thought I had RE: [Using Multiple Channels](https://github.com/rchain/rchain/blob/master/rspace/docs/Tutorial.md#using-multiple-channels):

I am a bit off-put by having two lists that need to be kept "lined up" for the `channels` and `patterns` arguments of the [consume method](https://github.com/rchain/rchain/blob/master/rspace/src/main/scala/coop/rchain/rspace/package.scala#L90). I'm newer to Scala, but it seems to me that in a larger application, you would want to keep the `pattern` and `channel` that are eventually passed to a consume closer together. Is there a reason that the function arguments are `channels: List[C], patterns: List[P]` and not something like `consumer: List[(C, P)]`?

**Comment by Jake-Gillberg** [comment]
I wonder what would happen in the following scenario:
1. objects `A` and `B` stored at Channel `C`
2. Pattern `P1` matches `A` and `B`
3. Pattern `P2` matches `A`
4. `consume` is called with `channels = List(C, C), patterns = List(P1, P2). If this is valid, it seems like these sorts of queries could explode in terms of run-time complexity as you increase the number of "terms" looking at the same channel in a consume.

Hmm.. it seems that the match works perfectly okay if the produces are followed by a consume, but I get a runtime exception the other way around:
```
  val consumeMayWork = consume(store,
                               List(Channel("friends"), Channel("friends")),
                               List(NameMatch("Lahblah"), CityMatch("Crystal Lake")),
                               new Printer, persist = false)

  val putA = produce(store, Channel("friends"), alice, persist = false)
  val putB = produce(store, Channel("friends"), bob, persist = false)
```
Produces:
```
Exception in thread "main" java.lang.IllegalArgumentException: removeJoin: List(Channel(friends), Channel(friends)) is not a member of List()
	at coop.rchain.rspace.LMDBStore.removeJoin(LMDBStore.scala:236)
	at coop.rchain.rspace.LMDBStore.removeJoin(LMDBStore.scala:23)
	at coop.rchain.rspace.package$.$anonfun$produce$2(package.scala:209)
	at coop.rchain.rspace.package$.$anonfun$produce$2$adapted(package.scala:204)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at coop.rchain.rspace.package$.$anonfun$produce$1(package.scala:204)
	at coop.rchain.rspace.LMDBStore.withTxn(LMDBStore.scala:61)
	at coop.rchain.rspace.LMDBStore.withTxn(LMDBStore.scala:23)
	at coop.rchain.rspace.package$.produce(package.scala:191)
	at tutorial$.delayedEndpoint$tutorial$1(tutorial.scala:172)
	at tutorial$delayedInit$body.apply(tutorial.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at tutorial$.main(tutorial.scala:7)
	at tutorial.main(tutorial.scala)
```

**Comment by TrenchFloat** [comment]
What's the next step for this issue? How can we tell when it's finished?

**Comment by dckc** [comment]
Following #301, I suggest this is done when the feedback is collected and delivered to the core dev team.

As to next steps... I suppose I should clarify that I don't see myself making time for this...

**Comment by TrenchFloat** [comment]
@cenyuhai @zsluedem might chime in with feedback here.

**Comment by zsluedem** [comment]
@TrenchFloat not really a scala developer. May find to time the take a look

**Comment by dckc** [comment]
The energy here seems to have petered out.
